---
services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped
    mem_limit: 1g
    mem_reservation: 256m
    user: "1000:1000"
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=${N8N_HOST}
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - NODE_ENV=production
      - WEBHOOK_URL=${WEBHOOK_URL}
      - GENERIC_TIMEZONE=${TZ}
      - TZ=${TZ}
    volumes:
      - ./data:/home/node/.n8n
    networks:
      - homelab

networks:
  homelab:
    external: true
    name: homelab
